=== ARM-software/arm-systemready/common/tools/test_categoryDT-schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://github.com/ARM-software/arm-systemready/blob/main/common/log_parser/test_categoryDT-schema.json",
	"title": "DT Test Categories",
	"description": "The description of ACS-Devicetree test categories",
	"$defs": {
		"catID": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"Suite": {
						"enum": [
							"BBSR-FWTS",
							"BBSR-SCT",
							"BBSR-Standalone",
							"BSA",
							"FWTS",
							"PFDI",
							"SCMI",
							"SCT",
							"Standalone"
						]
					},
					"Test Suite": {
						"enum": [
							"A/B support",
							"BASE",
							"Boot sources",
							"BootServicesTest",
							"CLOCK",
							"Capsule Update",
							"Capsule update",
							"ConsoleSupportTest",
							"Devicetree Blob Alignment Validation",
							"Devicetree Reserved Memory Validation",
						        "EBBR Spin-table Usage Validation",
							"DTValidation",
							"DevicePathProcotols",
							"EBBR requirements",
							"GIC",
							"GenericTest",
							"HIITest",
							"LinuxInstall",
							"LoadedImageProtocolTest",
							"MEM_MAP",
							"Measured boot log",
							"Network boot",
							"Network",
							"NetworkSupportTest",
							"PCIe",
							"PE",
							"PERFORMANCE",
							"PFDI",
							"PIN CONTROL",
							"POWER",
							"POWERCAP",
							"POWER_WAKEUP",
							"PSCI",
							"Peripheral",
							"Peripherals",
							"PlatformResetAttackMitigationPsciTest",
							"RESET",
							"RuntimeServicesTest",
							"SENSOR",
							"SMBIOS",
							"SMMU",
							"SYSTEM POWER",
							"SecureTechTest",
							"TCG2ProtocolTest",
							"Timer",
							"VOLTAGE",
							"Watchdog",
							"dt_base",
							"esrt",
							"smccc",
							"uefibootpath",
							"uefirtauthvar",
							"uefirtmisc",
							"uefirttime",
							"uefirtvariable",
							"uefivarinfo"
						]
					},
					"Description": {
						"type": "array",
						"item": { "type": "string" },
						"minItems": 1
					},
					"specName": {
						"enum": [
							"BBR",
							"BBSR",
							"BSA",
							"DT",
							"EBBR",
							"PFDI",
							"PSCI",
							"SCMI",
							"SRS",
							"UEFI"
						]
					},
					"rel Import. to main readiness": {
						"enum": ["Critical", "Minor"]
					},
					"Waivable": {
						"enum": ["no", "yes"]
					},
					"SRS scope": {
						"enum": ["Conditional Required", "Recommended", "Required"]
					},
					"FunctionID": {
						"type": "integer",
						"minimum": 1,
						"maximum": 9
					},
					"Main Readiness Grouping": {
						"enum": [
							"Misc readiness",
							"Physical readiness",
							"boot readiness",
							"maintenance readiness",
							"runtime readiness",
							"safety readiness",
							"security readiness"
						]
					}
				},
				"required": [
					"Description",
					"FunctionID",
					"Main Readiness Grouping",
					"SRS scope",
					"Suite",
					"Test Suite",
					"Waivable",
					"rel Import. to main readiness",
					"specName"
				],
				"additionalProperties": false
			},
			"minItems": 1,
			"maxItems": 1
		}
	},
	"type": "object",
	"properties": {
		"catID: 1": { "$ref": "#/$defs/catID" },
		"catID: 2": { "$ref": "#/$defs/catID" },
		"catID: 3": { "$ref": "#/$defs/catID" },
		"catID: 4": { "$ref": "#/$defs/catID" },
		"catID: 5": { "$ref": "#/$defs/catID" },
		"catID: 6": { "$ref": "#/$defs/catID" },
		"catID: 7": { "$ref": "#/$defs/catID" },
		"catID: 8": { "$ref": "#/$defs/catID" },
		"catID: 9": { "$ref": "#/$defs/catID" },
		"catID: 10": { "$ref": "#/$defs/catID" },
		"catID: 11": { "$ref": "#/$defs/catID" },
		"catID: 12": { "$ref": "#/$defs/catID" },
		"catID: 13": { "$ref": "#/$defs/catID" },
		"catID: 14": { "$ref": "#/$defs/catID" },
		"catID: 15": { "$ref": "#/$defs/catID" },
		"catID: 16": { "$ref": "#/$defs/catID" },
		"catID: 17": { "$ref": "#/$defs/catID" },
		"catID: 18": { "$ref": "#/$defs/catID" },
		"catID: 19": { "$ref": "#/$defs/catID" },
		"catID: 20": { "$ref": "#/$defs/catID" },
		"catID: 21": { "$ref": "#/$defs/catID" },
		"catID: 22": { "$ref": "#/$defs/catID" },
		"catID: 23": { "$ref": "#/$defs/catID" },
		"catID: 24": { "$ref": "#/$defs/catID" },
		"catID: 25": { "$ref": "#/$defs/catID" },
		"catID: 26": { "$ref": "#/$defs/catID" },
		"catID: 27": { "$ref": "#/$defs/catID" },
		"catID: 28": { "$ref": "#/$defs/catID" },
		"catID: 29": { "$ref": "#/$defs/catID" },
		"catID: 30": { "$ref": "#/$defs/catID" },
		"catID: 31": { "$ref": "#/$defs/catID" },
		"catID: 32": { "$ref": "#/$defs/catID" },
		"catID: 33": { "$ref": "#/$defs/catID" },
		"catID: 34": { "$ref": "#/$defs/catID" },
		"catID: 35": { "$ref": "#/$defs/catID" },
		"catID: 36": { "$ref": "#/$defs/catID" },
		"catID: 37": { "$ref": "#/$defs/catID" },
		"catID: 38": { "$ref": "#/$defs/catID" },
		"catID: 39": { "$ref": "#/$defs/catID" },
		"catID: 40": { "$ref": "#/$defs/catID" },
		"catID: 41": { "$ref": "#/$defs/catID" },
		"catID: 42": { "$ref": "#/$defs/catID" },
		"catID: 43": { "$ref": "#/$defs/catID" },
		"catID: 44": { "$ref": "#/$defs/catID" },
		"catID: 45": { "$ref": "#/$defs/catID" },
		"catID: 46": { "$ref": "#/$defs/catID" },
		"catID: 47": { "$ref": "#/$defs/catID" },
		"catID: 48": { "$ref": "#/$defs/catID" },
		"catID: 49": { "$ref": "#/$defs/catID" },
		"catID: 50": { "$ref": "#/$defs/catID" },
		"catID: 51": { "$ref": "#/$defs/catID" },
		"catID: 52": { "$ref": "#/$defs/catID" },
		"catID: 53": { "$ref": "#/$defs/catID" },
		"catID: 54": { "$ref": "#/$defs/catID" },
		"catID: 55": { "$ref": "#/$defs/catID" },
		"catID: 56": { "$ref": "#/$defs/catID" },
		"catID: 57": { "$ref": "#/$defs/catID" }
	},
	"required": [
		"catID: 1",
		"catID: 2",
		"catID: 3",
		"catID: 4",
		"catID: 5",
		"catID: 6",
		"catID: 7",
		"catID: 8",
		"catID: 9",
		"catID: 10",
		"catID: 11",
		"catID: 12",
		"catID: 13",
		"catID: 14",
		"catID: 15",
		"catID: 16",
		"catID: 17",
		"catID: 18",
		"catID: 19",
		"catID: 20",
		"catID: 21",
		"catID: 22",
		"catID: 23",
		"catID: 24",
		"catID: 25",
		"catID: 26",
		"catID: 27",
		"catID: 28",
		"catID: 29",
		"catID: 30",
		"catID: 31",
		"catID: 32",
		"catID: 33",
		"catID: 34",
		"catID: 35",
		"catID: 36",
		"catID: 37",
		"catID: 38",
		"catID: 39",
		"catID: 40",
		"catID: 41",
		"catID: 42",
		"catID: 43",
		"catID: 44",
		"catID: 45",
		"catID: 46",
		"catID: 47",
		"catID: 48",
		"catID: 49",
		"catID: 50",
		"catID: 51",
		"catID: 52",
		"catID: 53",
		"catID: 54",
		"catID: 55",
		"catID: 56",
		"catID: 57"
	],
	"additionalProperties": false
}

=== ARM-software/arm-systemready/common/log_parser/test_categoryDT.json
{
  "catID: 1": [
    {
      "Suite": "BSA",
      "Test Suite": "PE",
      "Description": [
        "The Base System Architecture (BSA) Platform Design Document specifies a hardware system architecture that operating systems, hypervisors, and firmware can rely on.",
        "The SystemReady Devicetree band recommends compliance with BSA requirements.",
        "BSA PE tests verify BSA requirements on the Processing Element (PE).",
        "Failures may have only minor effects, or may prevent an OS to boot.",
        "https://github.com/ARM-software/sysarch-acs"
      ],
      "specName": "BSA",
      "rel Import. to main readiness": "Critical",
      "Waivable": "yes",
      "SRS scope": "Recommended",
      "FunctionID": 9,
      "Main Readiness Grouping": "Physical readiness"
    }
  ],
  "catID: 2": [
    {
      "Suite": "BSA",
      "Test Suite": "GIC",
      "Description": [
        "The Base System Architecture (BSA) Platform Design Document specifies a hardware system architecture that operating systems, hypervisors, and firmware can rely on.",
        "The SystemReady Devicetree band recommends compliance with BSA requirements.",
        "BSA GIC tests verify BSA requirements on the Generic Interrupt Controller (GIC).",
        "The GIC delivers interrupts to the Processing Elements (PEs).",
        "Failures may have only minor effects, or may prevent an OS to boot.",
        "https://github.com/ARM-software/sysarch-acs"
      ],
      "specName": "BSA",
      "rel Import. to main readiness": "Critical",
      "Waivable": "yes",
      "SRS scope": "Recommended",
      "FunctionID": 9,
      "Main Readiness Grouping": "Physical readiness"
    }
  ],
  "catID: 3": [
    {
      "Suite": "BSA",
      "Test Suite": "SMMU",
      "Description": [
        "The Base System Architecture (BSA) Platform Design Document specifies a hardware system architecture that operating systems, hypervisors, and firmware can rely on.",
        "The SystemReady Devicetree band recommends compliance with BSA requirements.",
        "BSA SMMU tests verify BSA requirements on the System Memory Management Unit (SMMU).",
        "An SMMU translates addresses from devices capable of Direct Memory Access (DMA).",
        "Failures may have only minor effects, or may prevent an OS to boot.",
        "https://github.com/ARM-software/sysarch-acs"
      ],
      "specName": "BSA",
      "rel Import. to main readiness": "Critical",
      "Waivable": "yes",
      "SRS scope": "Recommended",
      "FunctionID": 9,
      "Main Readiness Grouping": "Physical readiness"
    }
  ],
  "catID: 4": [
    {
      "Suite": "BSA",
      "Test Suite": "PCIe",
      "Description": [
        "The Base System Architecture (BSA) Platform Design Document specifies a hardware system architecture that operating systems, hypervisors, and firmware can rely on.",
        "The SystemReady Devicetree band recommends compliance with BSA requirements.",
        "BSA PCIe tests verify BSA requirements on PCI Express (PCIe) integration.",
        "Failures may have only minor effects, or may prevent an OS to boot.",
        "https://github.com/ARM-software/sysarch-acs"
      ],
      "specName": "BSA",
      "rel Import. to main readiness": "Minor",
      "Waivable": "yes",
      "SRS scope": "Recommended",
      "FunctionID": 9,
      "Main Readiness Grouping": "Physical readiness"
    }
  ],
  "catID: 5": [
    {
      "Suite": "BSA",
      "Test Suite": "Timer",
      "Description": [
        "The Base System Architecture (BSA) Platform Design Document specifies a hardware system architecture that operating systems, hypervisors, and firmware can rely on.",
        "The SystemReady Devicetree band recommends compliance with BSA requirements.",
        "BSA Timer tests verify BSA requirements on the clock and timer subsystem.",
        "Failures may have only minor effects, or may prevent an OS to boot.",
        "https://github.com/ARM-software/sysarch-acs"
      ],
      "specName": "BSA",
      "rel Import. to main readiness": "Minor",
      "Waivable": "yes",
      "SRS scope": "Recommended",
      "FunctionID": 9,
      "Main Readiness Grouping": "Physical readiness"
    }
  ],
  "catID: 6": [
    {
      "Suite": "BSA",
      "Test Suite": "Peripheral",
      "Description": [
        "The Base System Architecture (BSA) Platform Design Document specifies a hardware system architecture that operating systems, hypervisors, and firmware can rely on.",
        "The SystemReady Devicetree band recommends compliance with BSA requirements.",
        "BSA Peripheral tests verify BSA requirements on the peripheral subsystems (USB, SATA, UART).",
        "Failures may have only minor effects, or may prevent an OS to boot.",
        "https://github.com/ARM-software/sysarch-acs"
      ],
      "specName": "BSA",
      "rel Import. to main readiness": "Minor",
      "Waivable": "yes",
      "SRS scope": "Recommended",
      "FunctionID": 9,
      "Main Readiness Grouping": "Physical readiness"
    }
  ],
  "catID: 7": [
    {
      "Suite": "BSA",
      "Test Suite": "Watchdog",
      "Description": [
        "The Base System Architecture (BSA) Platform Design Document specifies a hardware system architecture that operating systems, hypervisors, and firmware can rely on.",
        "The SystemReady Devicetree band recommends compliance with BSA requirements.",
        "BSA Watchdog tests verify BSA requirements on the Generic Watchdog.",
	"Failures are not expected to prevent an OS from booting.",
        "https://github.com/ARM-software/sysarch-acs"
      ],
      "specName": "BSA",
      "rel Import. to main readiness": "Minor",
      "Waivable": "yes",
      "SRS scope": "Recommended",
      "FunctionID": 9,
      "Main Readiness Grouping": "Physical readiness"
    }
  ],
  "catID: 8": [
    {
      "Suite": "BSA",
      "Test Suite": "POWER_WAKEUP",
      "Description": [
        "The Base System Architecture (BSA) Platform Design Document specifies a hardware system architecture that operating systems, hypervisors, and firmware can rely on.",
        "The SystemReady Devicetree band recommends compliance with BSA requirements.",
        "BSA POWER_WAKEUP tests verify BSA requirements on the wakeup and power state semantics.",
	"Failures are not expected to prevent an OS from booting.",
        "https://github.com/ARM-software/sysarch-acs"
      ],
      "specName": "BSA",
      "rel Import. to main readiness": "Minor",
      "Waivable": "yes",
      "SRS scope": "Recommended",
      "FunctionID": 9,
      "Main Readiness Grouping": "Physical readiness"
    }
  ],
  "catID: 9": [
    {
      "Suite": "BSA",
      "Test Suite": "MEM_MAP",
      "Description": [
        "The Base System Architecture (BSA) Platform Design Document specifies a hardware system architecture that operating systems, hypervisors, and firmware can rely on.",
        "The SystemReady Devicetree band recommends compliance with BSA requirements.",
        "BSA MEM_MAP tests verify BSA requirements on the system's memory map.",
        "Failures may have only minor effects, or may prevent an OS to boot.",
        "https://github.com/ARM-software/sysarch-acs"
      ],
      "specName": "BSA",
      "rel Import. to main readiness": "Minor",
      "Waivable": "yes",
      "SRS scope": "Recommended",
      "FunctionID": 9,
      "Main Readiness Grouping": "Physical readiness"
    }
  ],
  "catID: 10": [
    {
      "Suite": "FWTS",
      "Test Suite": "uefivarinfo",
      "Description": [
        "The EBBR specification defines a subset of UEFI provided to an OS.",
        "The Firmware Test Suite (FWTS) is a test suite that performs sanity checks on firmware.",
	"The uefivarinfo FWTS tests verify requirements on UEFI Variables services.",
	"Failures are not expected to prevent an OS from booting.",
        "https://wiki.ubuntu.com/FirmwareTestSuite"
      ],
      "specName": "EBBR",
      "rel Import. to main readiness": "Critical",
      "Waivable": "no",
      "SRS scope": "Required",
      "FunctionID": 2,
      "Main Readiness Grouping": "maintenance readiness"
    }
  ],
  "catID: 11": [
    {
      "Suite": "FWTS",
      "Test Suite": "uefirtmisc",
      "Description": [
        "The EBBR specification defines a subset of UEFI provided to an OS.",
        "The Firmware Test Suite (FWTS) is a test suite that performs sanity checks on firmware.",
	"The uefirtmisc FWTS tests verify requirements on miscellaneous UEFI Runtime services.",
	"This comprises monotonic counter and capsule services.",
	"Failures may have only minor effects, or may prevent firmware update.",
        "https://wiki.ubuntu.com/FirmwareTestSuite"
      ],
      "specName": "EBBR",
      "rel Import. to main readiness": "Critical",
      "Waivable": "no",
      "SRS scope": "Required",
      "FunctionID": 6,
      "Main Readiness Grouping": "Misc readiness"
    }
  ],
  "catID: 12": [
    {
      "Suite": "FWTS",
      "Test Suite": "esrt",
      "Description": [
        "The EBBR specification defines a subset of UEFI provided to an OS.",
        "The Firmware Test Suite (FWTS) is a test suite that performs sanity checks on firmware.",
	"The esrt FWTS tests verify requirements on the EFI System Resource Table (ESRT).",
	"Failures may have only minor effects, or may prevent firmware update.",
        "https://wiki.ubuntu.com/FirmwareTestSuite"
      ],
      "specName": "EBBR",
      "rel Import. to main readiness": "Critical",
      "Waivable": "no",
      "SRS scope": "Required",
      "FunctionID": 2,
      "Main Readiness Grouping": "maintenance readiness"
    }
  ],
  "catID: 13": [
    {
      "Suite": "FWTS",
      "Test Suite": "uefirttime",
      "Description": [
        "The EBBR specification defines a subset of UEFI provided to an OS.",
        "The Firmware Test Suite (FWTS) is a test suite that performs sanity checks on firmware.",
